"""remove history tables

Revision ID: 6472b643df68
Revises: 208efaf6f3d9
Create Date: 2022-03-07 18:43:09.484837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6472b643df68'
down_revision = '208efaf6f3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernamehistory')
    op.drop_table('connectionhistory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectionhistory',
    sa.Column('event_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_connected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='connectionhistory_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usernamehistory',
    sa.Column('event_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_username', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('new_username', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('date', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='usernamehistory_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
