"""Date chaged from float to datetime

Revision ID: d727fb605438
Revises: 24763aef4f73
Create Date: 2022-02-08 21:50:33.052145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd727fb605438'
down_revision = '24763aef4f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'date',
               existing_type=mysql.FLOAT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'date',
               existing_type=sa.DateTime(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
